    upstream mtdomain {
        #ip_hash;  # 使用 IP Hash 分配請求
        server 10.10.28.32:8080;
        # server 172.30.16.1:8080; #實體位置
    }

    upstream google {
        #ip_hash;  # 使用 IP Hash 分配請求
        server 142.250.204.36;
    }

    
    upstream mkdocs {
        #ip_hash;  # 使用 IP Hash 分配請求
        server 10.10.28.32:3002;
        # server 172.30.16.1:3002; #實體位置
    }